"""empty message

Revision ID: 1018b5941ca
Revises: 33009138b25
Create Date: 2020-06-26 15:05:57.940185

"""

# revision identifiers, used by Alembic.
revision = '1018b5941ca'
down_revision = '33009138b25'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
