"""empty message

Revision ID: 125f540c665
Revises: 473b3171bd2
Create Date: 2020-06-26 16:11:00.398032

"""

# revision identifiers, used by Alembic.
revision = '125f540c665'
down_revision = '473b3171bd2'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
