"""empty message

Revision ID: 157738e54a8
Revises: 
Create Date: 2020-07-07 19:40:30.966258

"""

# revision identifiers, used by Alembic.
revision = '157738e54a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
