"""empty message

Revision ID: 33009138b25
Revises: 
Create Date: 2020-06-26 14:53:04.430187

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '33009138b25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.create_unique_constraint('name', ['name'])

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.create_unique_constraint('hosp_name', ['hosp_name'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint('name', ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('age',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('bld_donation',
                              existing_type=sa.BOOLEAN(),
                              nullable=False)
        batch_op.alter_column('bld_grp',
                              existing_type=sa.VARCHAR(length=5),
                              nullable=True)
        batch_op.alter_column('pan',
                              existing_type=sa.VARCHAR(length=10),
                              nullable=True)
        batch_op.alter_column('po_num',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.create_unique_constraint('mobile', ['mobile'])
        batch_op.create_unique_constraint('aadhar', ['aadhar'])
        batch_op.create_unique_constraint('username', ['username'])
        batch_op.create_unique_constraint('email', ['email'])
        batch_op.create_unique_constraint('pan', ['pan'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('mobile')
        batch_op.drop_constraint('aadhar')
        batch_op.drop_constraint('username')
        batch_op.drop_constraint('email')
        batch_op.drop_constraint('pan')
        batch_op.alter_column('po_num',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('pan',
                              existing_type=sa.VARCHAR(length=10),
                              nullable=False)
        batch_op.alter_column('bld_grp',
                              existing_type=sa.VARCHAR(length=5),
                              nullable=False)
        batch_op.alter_column('bld_donation',
                              existing_type=sa.BOOLEAN(),
                              nullable=True)
        batch_op.alter_column('age',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('name')

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_constraint('hosp_name')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_constraint('name')

    ### end Alembic commands ###
