"""empty message

Revision ID: 45ff5ab8f5e
Revises: 4b87c4426d3
Create Date: 2020-07-29 17:10:56.661269

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '45ff5ab8f5e'
down_revision = '4b87c4426d3'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('pan')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('pan', ['pan'])

    ### end Alembic commands ###
