"""empty message

Revision ID: 473b3171bd2
Revises: 485c909b453
Create Date: 2020-06-26 15:32:57.317204

"""

# revision identifiers, used by Alembic.
revision = '473b3171bd2'
down_revision = '485c909b453'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
