"""empty message

Revision ID: 485c909b453
Revises: 2f771e2236c
Create Date: 2020-06-26 15:14:55.733102

"""

# revision identifiers, used by Alembic.
revision = '485c909b453'
down_revision = '2f771e2236c'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
