"""empty message

Revision ID: 4a699942db6
Revises: 
Create Date: 2020-07-20 19:10:31.576965

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4a699942db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=40), nullable=True))
        batch_op.drop_column('uid')

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=40), nullable=True))
        batch_op.drop_column('uid')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(), nullable=True))
        batch_op.drop_column('uid')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=40), nullable=True))
        batch_op.drop_column('uid')

    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=40), nullable=True))
        batch_op.drop_column('uid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=40), nullable=True))
        batch_op.drop_column('uid')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('scheme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.INTEGER(), nullable=True))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('uuid')

    ### end Alembic commands ###
