"""empty message

Revision ID: 4b87c4426d3
Revises: 4a699942db6
Create Date: 2020-07-20 22:50:54.855093

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4b87c4426d3'
down_revision = '4a699942db6'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hosp_id', sa.String(), nullable=True))
        batch_op.drop_column('id')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('hosp_id')

    ### end Alembic commands ###
