"""empty message

Revision ID: 52f46e5ad5f
Revises: 45ff5ab8f5e
Create Date: 2020-07-30 09:53:38.124124

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '52f46e5ad5f'
down_revision = '45ff5ab8f5e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
                    sa.Column('uuid', sa.String(length=40), nullable=False),
                    sa.Column('grad_country', sa.String(length=100), nullable=False),
                    sa.Column('reg_no', sa.Integer(), nullable=False),
                    sa.Column('specialization', sa.String(), nullable=False),
                    sa.Column('experience', sa.Integer(), nullable=False),
                    sa.Column('work_location', sa.String(length=100), nullable=False),
                    sa.Column('work_hrs', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('uuid'),
                    sa.UniqueConstraint('reg_no'),
                    sa.UniqueConstraint('uuid')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor')
    ### end Alembic commands ###
