"""empty message

Revision ID: a1edd8ffc7
Revises: 1018b5941ca
Create Date: 2020-06-26 15:08:43.480599

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a1edd8ffc7'
down_revision = '1018b5941ca'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('organ_donation',
                              existing_type=sa.BOOLEAN(),
                              nullable=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('organ_donation',
                              existing_type=sa.BOOLEAN(),
                              nullable=True)

    ### end Alembic commands ###
